version: "3.9"
services:
  scrapper_web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=scrapping
      - DB_USER=postgres
      - DB_PASS=postgres

    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=scrapping
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
